name: GeoMamba
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2024.12.31=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.2=py39h06a4308_0
  - python=3.9.12=h12debd9_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2024b=h04d1e81_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==2.2.2
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.10
    - aiosignal==1.3.1
    - ase==3.26.0
    - astunparse==1.6.3
    - async-timeout==5.0.1
    - attrs==24.2.0
    - blosc2==2.5.1
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - contourpy==1.3.0
    - cycler==0.12.1
    - deap==1.4.3
    - decorator==5.2.1
    - deepdish==0.3.7
    - einops==0.7.0
    - filelock==3.13.1
    - flatbuffers==25.2.10
    - fonttools==4.55.2
    - frozenlist==1.5.0
    - fsspec==2024.2.0
    - gast==0.6.0
    - google-pasta==0.2.0
    - googledrivedownloader==1.1.0
    - grpcio==1.71.0
    - h5py==3.14.0
    - idna==3.10
    - imbalanced-learn==0.12.4
    - imblearn==0.0
    - importlib_metadata==8.7.0
    - importlib_resources==6.4.5
    - isodate==0.7.2
    - jinja2==3.1.3
    - joblib==1.3.2
    - keras==3.10.0
    - kiwisolver==1.4.7
    - lazy_loader==0.4
    - libclang==18.1.1
    - llvmlite==0.43.0
    - lxml==5.4.0
    - markdown==3.8
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.3
    - mdurl==0.1.2
    - ml_dtypes==0.5.1
    - mne==1.8.0
    - mpmath==1.3.0
    - msgpack==1.1.1
    - multidict==6.1.0
    - namex==0.1.0
    - ndindex==1.10.0
    - networkx==3.2.1
    - nibabel==5.3.2
    - nilearn==0.11.1
    - nipy==0.6.1
    - numba==0.60.0
    - numexpr==2.10.2
    - numpy==1.26.3
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-nccl-cu11==2.21.5
    - nvidia-nccl-cu12==2.27.3
    - nvidia-nvtx-cu11==11.8.86
    - opt_einsum==3.4.0
    - optree==0.16.0
    - packaging==24.2
    - pandas==2.2.3
    - pandas_flavor==0.7.0
    - patsy==1.0.1
    - pillow==10.2.0
    - pingouin==0.5.5
    - platformdirs==4.3.7
    - pooch==1.8.2
    - propcache==0.2.1
    - protobuf==5.29.5
    - psutil==6.1.0
    - py-cpuinfo==9.0.0
    - pygments==2.19.1
    - pynndescent==0.5.13
    - pyparsing==3.2.0
    - python-dateutil==2.8.2
    - python-louvain==0.16
    - pytz==2024.2
    - rdflib==7.1.4
    - requests==2.32.3
    - rich==14.0.0
    - scikit-learn==1.5.2
    - scipy==1.13.1
    - seaborn==0.13.2
    - six==1.17.0
    - statsmodels==0.14.4
    - sympy==1.13.1
    - tables==3.9.2
    - tabulate==0.9.0
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.4
    - tensorflow==2.19.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==3.1.0
    - threadpoolctl==3.5.0
    - torch==2.5.1+cu118
    - torch-geometric==2.6.1
    - torch_scatter==2.1.2+pt25cu118
    - torch_sparse==0.6.18+pt25cu118
    - torchaudio==2.5.1+cu118
    - torchinfo==1.8.0
    - torchvision==0.20.1+cu118
    - tqdm==4.67.1
    - transforms3d==0.4.2
    - triton==3.1.0
    - typing_extensions==4.9.0
    - umap==0.1.1
    - umap-learn==0.5.7
    - urllib3==2.2.3
    - werkzeug==3.1.3
    - wrapt==1.17.2
    - xarray==2024.7.0
    - xgboost==2.1.4
    - yarl==1.18.3
    - zipp==3.21.0
prefix: /home/ms/anaconda3/envs/GeoMamba

